In [1]:
import numpy as np
import pandas as pd

In [2]:
#read dataset using pandas
data=pd.read_csv("train_and_test2.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'train_and_test2.csv'

In [2]:
import numpy as np
import pandas as pd

In [9]:
data=pd.read_csv(r"C:\Users\khush\Downloads\Titanic-Dataset.csv")

In [10]:
data.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [ ]:
import numpy as np

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv(r"C:\Users\khush\Downloads\Titanic-Dataset.csv")

In [4]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
data.rename(columns={
    'PassengerId':'Passenger_Id','Pclass':'Passenger_Class','Name':'Passenger_Name','Sex':'Gender','Age':'Passenger_Age','SibSp':'Siblings_Spouse_Aboard','Parch':'Parents_Children_Aboard','Ticket':'Ticket_Number','Fare':'Ticket_Fare','Cabin':'Cabin_Number','Embarked':'Port_of_Embarkation'}, inplace=True)

In [6]:
data.head()

,Passenger_Id,Survived,Passenger_Class,Passenger_Name,Gender,Passenger_Age,Siblings_Spouse_Aboard,Parents_Children_Aboard,Ticket_Number,Ticket_Fare,Cabin_Number,Port_of_Embarkation
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
data['Siblings_Spouse_Aboard'].value_counts()

Siblings_Spouse_Aboard
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64